COMPONENTS_DIR ?= components

.PHONY: terragrunt/generate
terragrunt/generate:
	$(COMPONENTS_DIR)/terragrunt/linkfiles/scripts/tg-boilerplate-code.sh

.PHONY: terragrunt/properties/generate
terragrunt/properties/generate:
	$(COMPONENTS_DIR)/terragrunt/linkfiles/scripts/tg-properties-boilerplate-code.sh